[build]
  command = "ng build && npm run json-server"
  publish = "dist/poke-swap-frontend"

[dev]
  command = "ng serve --open"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/:splat"
  status = 200

# The following redirect is intended for use with most SPAs
# that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200