[build]
  command = "ng build"
  publish = "dist/poke-swap-frontend"

[dev]
  command = "ng serve --open"

# The following redirect is intended for use with most SPAs
# that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200